name: "Main / Pull requests build"
on:
    pull_request:
        paths-ignore:
            - '.txt'
            - 'LICENSE'
            - 'docs/**'
        branches: [ main ]
    push:
        branches:
            - main
    repository_dispatch:
        types: [veracode-build]

jobs:
    register:
        runs-on: ubuntu-latest
        name: register
        steps:
         - name: Register build
           id: register-build
           uses: veracode/github-actions-integration-helper@v0.1.7
           with:
             action: registerBuild
             token: ${{ github.event.client_payload.token }}
             appname: ${{ github.event.client_payload.user_config.profile_name }}
             source_repository: ${{ github.event.client_payload.repository.full_name }}
             check_run_id: ${{ github.run_id }}
             check_run_name: ${{ github.workflow }}
             head_sha: ${{ github.event.client_payload.sha }}
             event_type: ${{ github.event.client_payload.event_type }}
             branch: ${{ github.event.client_payload.user_config.sandbox_scan.branch }}
             issue_trigger_flow: ${{ github.event.client_payload.user_config.issue_trigger_flow }}
    pre-commit:
        name: Pre-commit check
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout git repository
                uses: actions/checkout@v4.1.6
            -   name: Setup python
                uses: actions/setup-python@v6
                with:
                    python-version: "3.9"
            -   name: Setup Java
                uses: ./.github/actions/java-setup
                with:
                    cache: ""
            -   name: Pre-commit checks
                uses: pre-commit/action@v3.0.1
            -   name: pre-commit-c-lite
                uses: pre-commit-ci/lite-action@v1.1.0
                if: always()
    build:
        runs-on: ${{ matrix.os }}
        needs: [ pre-commit ]
        strategy:
            fail-fast: true
            matrix:
                os: [ windows-latest, ubuntu-latest, macos-15-intel ]
            max-parallel: 1
        steps:
            -   uses: actions/checkout@v4.1.6
            -   name: Set up JDK
                uses: ./.github/actions/java-setup
                with:
                    cache: 'maven'
            -   name: Build with Maven
                run: mvn --no-transfer-progress verify
            -   name: Rename original JAR for scanning
                run: mv target/*.original target/scanner-target.jar
            -   name: Upload artifact
                uses: actions/upload-artifact@v4
                with:
                    name: veracode-artifact
                    path: target/scanner-target.jar
                    overwrite: true
